In [1]:
import json
import pandas as pd

In [2]:
path = '../data/characters_detail_parallel.json'
with open(path, 'r') as file:
    # Load the JSON data from the file
    data = json.load(file)

In [4]:
new_data = []
for d in data:
    keys = d.keys()
    new_id = list(keys)[0]
    detail = d[new_id]
    detail['id'] = new_id
    new_data.append(detail)
df = pd.DataFrame(new_data)
print(df)

           jname           rname  \
0        [シャンクス]      [Shankusu]
1     [ベン・ベックマン]  [Ben Bekkuman]
2      [ラッキー・ルウ]      [Rakkī Rū]
3         [ヤソップ]       [Yasoppu]
4      [ライムジュース]     [Raimujūsu]
...          ...             ...
1368         NaN             NaN
1369  [ピープリー･ルル]   [Pīpurī Ruru]
1370      [クラップ]       [Kurappu]
1371       [ジニー]          [Jinī]
1372       [ベコリ]        [Bekori]

                                               ename  \
0                                           [Shanks]
1        [Benn Beckman, Ben Beckman (VIZ, formerly)]
2                    [Lucky Roux, Lucky Roo (WT100)]
3                                           [Yasopp]
4                                       [Lime Juice]
...                                              ...
1368                                             NaN
1369  [Peepley Lulu (Viz), Peeply Lulu (Funimation)]
1370                                         [Clapp]
1371                                         [Ginny]
1372                                        [Bekori]

                           first  \
0         [Chapter 1, Episode 4]
1         [Chapter 1, Episode 4]
2         [Chapter 1, Episode 4]
3         [Chapter 1, Episode 4]
4         [Chapter 1, Episode 4]
...                          ...
1368                         NaN
1369  [Chapter 323, Episode 230]
1370              [Chapter 1095]
1371              [Chapter 1095]
1372              [Chapter 1097]

                                            affiliation  \
0     [Red Hair Pirates, Four Emperors, Roger Pirate...
1                                    [Red Hair Pirates]
2                                    [Red Hair Pirates]
3                                    [Red Hair Pirates]
4                                    [Red Hair Pirates]
...                                                 ...
1368                                                NaN
1369                                [Galley-La Company]
1370                                                NaN
1371  [Revolutionary Army (East Army), Freedom Fight...
1372                                                NaN

                                             occupation  \
0                 [Chief, Emperor, Apprentice (former)]
1                                  [Pirate, First Mate]
2             [Pirate, Senior Officer, Combatant, Cook]
3                      [Pirate, Senior Officer, Sniper]
4                              [Pirate, Senior Officer]
...                                                 ...
1368                                                NaN
1369                     [Dock One Foreman, Shipwright]
1370                   [Slave, Church manager (former)]
1371  [East Army Captain of the Revolutionary Army, ...
1372                                    [King (former)]

                           origin                epithet      status  \
0                     [West Blue]  ["Red-Haired Shanks"]     [Alive]
1                    [North Blue]                    NaN     [Alive]
2                    [South Blue]                    NaN     [Alive]
3     [East Blue (Gecko Islands)]             ["Chaser"]     [Alive]
4                             NaN                    NaN     [Alive]
...                           ...                    ...         ...
1368                          NaN                    NaN         NaN
1369       [Grand Line (Water 7)]                    NaN     [Alive]
1370             [Sorbet Kingdom]                    NaN  [Deceased]
1371                          NaN                    NaN  [Deceased]
1372                          NaN                    NaN   [Unknown]

                                                    age  ... dfname2 dfename2  \
0     [27 (debut), 37 (pre-timeskip), 39 (after time...  ...     NaN      NaN
1     [38 (debut), 48 (pre-timeskip), 50 (after time...  ...     NaN      NaN
2     [23 (debut), 33 (pre-timeskip), 35 (after time...  ...     NaN      NaN
3     [35 (debut), 45 (pre-timeskip), 47 (after time...  ...     NaN      NaN
4                                                   NaN  ...     NaN      NaN
...                                                 ...  ...     ...      ...
1368                                                NaN  ...     NaN      NaN
1369                  [31 (debut), 33 (after timeskip)]  ...     NaN      NaN
1370                                                NaN  ...     NaN      NaN
1371                                                NaN  ...     NaN      NaN
1372                                                NaN  ...     NaN      NaN

     dfmeaning2 dftype2 size weight doriki cp9key zombie number  \
0           NaN     NaN  NaN    NaN    NaN    NaN           NaN
1           NaN     NaN  NaN    NaN    NaN    NaN           NaN
2           NaN     NaN  NaN    NaN    NaN    NaN           NaN
3           NaN     NaN  NaN    NaN    NaN    NaN           NaN
4           NaN     NaN  NaN    NaN    NaN    NaN           NaN
...         ...     ...  ...    ...    ...    ...           ...
1368        NaN     NaN  NaN    NaN    NaN    NaN           NaN
1369        NaN     NaN  NaN    NaN    NaN    NaN           NaN
1370        NaN     NaN  NaN    NaN    NaN    NaN           NaN
1371        NaN     NaN  NaN    NaN    NaN    NaN           NaN
1372        NaN     NaN  NaN    NaN    NaN    NaN           NaN

     gladiator number
0                 NaN
1                 NaN
2                 NaN
3                 NaN
4                 NaN
...               ...
1368              NaN
1369              NaN
1370              NaN
1371              NaN
1372              NaN

[1373 rows x 38 columns]

In [25]:
from IPython.display import display, HTML
# Assuming df is your DataFrame
non_nan_counts = df.count().sort_values(ascending=False)
non_nan_counts_df = non_nan_counts.to_frame(name='available')
# print(non_nan_counts_df)
max_value = non_nan_counts_df['available'].max()
non_nan_counts_df['percentage'] = ((non_nan_counts_df['available'] / max_value) * 100).round(2)

# # Split the Series into two parts
split_index = len(non_nan_counts_df) // 2
first_part = non_nan_counts_df[:split_index]
second_part = non_nan_counts_df[split_index:]

# # # Display the two parts as separate HTML tables
display(HTML(first_part.to_html()))
display(HTML(second_part.to_html()))