In [10]:
import pandas as pd
from IPython.display import display, HTML

In [8]:
path = '../data/characters_detail_parallel.json'
df = pd.read_json(path, orient='records')

In [9]:
df.columns

Index(['id', 'jname', 'rname', 'ename', 'first', 'affiliation', 'occupation',
       'origin', 'epithet', 'status', 'age', 'birth', 'height', 'blood type',
       'bounty', 'jva', 'Odex eva', '4kids eva', 'Funi eva', 'liveaction',
       'residence', 'alias', 'age2', 'dfname', 'dfename', 'dfmeaning',
       'dftype', 'birthname', 'dfname2', 'dfename2', 'dfmeaning2', 'dftype2',
       'size', 'weight', 'doriki', 'cp9key', 'zombie number',
       'gladiator number'],
      dtype='object')

In [11]:
# Assuming df is your DataFrame
non_nan_counts = df.count().sort_values(ascending=False)
non_nan_counts_df = non_nan_counts.to_frame(name='available')
# print(non_nan_counts_df)
max_value = non_nan_counts_df['available'].max()
non_nan_counts_df['percentage'] = ((non_nan_counts_df['available'] / max_value) * 100).round(2)

# # Split the Series into two parts
split_index = len(non_nan_counts_df) // 2
first_part = non_nan_counts_df[:split_index]
second_part = non_nan_counts_df[split_index:]

# # # Display the two parts as separate HTML tables
display(HTML(first_part.to_html()))
display(HTML(second_part.to_html()))

In [18]:
def contains_list(element):
    return isinstance(element, list)
contains_list_df = df.map(contains_list)
columns_with_lists = contains_list_df.any()
print(columns_with_lists[columns_with_lists].index.to_list())
print(len(columns_with_lists[columns_with_lists].index.to_list()))

['jname', 'rname', 'ename', 'first', 'affiliation', 'occupation', 'origin', 'epithet', 'status', 'age', 'birth', 'height', 'blood type', 'bounty', 'jva', 'Odex eva', '4kids eva', 'Funi eva', 'liveaction', 'residence', 'alias', 'age2', 'dfname', 'dfename', 'dfmeaning', 'dftype', 'birthname', 'dfname2', 'dfename2', 'dfmeaning2', 'dftype2', 'size', 'weight', 'doriki', 'cp9key', 'zombie number', 'gladiator number']
37

In [20]:
df.to_csv('../data/characters_detail.csv', index=False)

In [31]:
filtered_df = df[df['ename'].apply(lambda x: isinstance(x, list) and len(x) > 3)]

print(filtered_df['ename'])

197    [Eyelashes (Viz),, Eyelash (4Kids, FUNimation ...
256    [Mont Blanc Cricket (Viz),, Montblanc Cricket ...
278    [Ganfor (VIZ, Funimation simulcast), Gan Fall ...
Name: ename, dtype: object

In [41]:
df.iloc[197]['ename']

['Eyelashes (Viz),',
 'Eyelash (4Kids, FUNimation dub),',
 'Lashes (FUNimation subs),',
 'Matsuge (WT100)']